version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  springbootapp:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongodb_data_container:
